//#include <bits/stdc++.h>
#include <iostream>
#include <vector>
using namespace std;

#define ll long long
#define ull unsigned long long
#define Endl cout << '\n';
#define nbsp cout << " ";
#define fon(i, n) for (ll int i = 0; i < n; i++)

void file_io()
{

    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
#ifndef ONLINE_JUDGE
    freopen("in.txt", "r", stdin);
    freopen("out.txt", "w+", stdout);
#else
    // online submission
#endif
}
void solve()
{
    int h = 0;
    float c = 0, t = 0;
    cin >> h >> c >> t;

    switch (grade)
    {
    case:
        /* code */
        break;

    default:
        break;
    }
}
int main()
{
    file_io();
    ll int t;
    cin >> t;
    do
    {
        solve();
        t--;
    } while (t != 0);

    return 0;
}