#include <bits/stdc++.h>

using namespace std;

#define ll long long
#define ull unsigned long long
#define ENDL cout << '\n'
#define nbsp cout << " "

void solve()
{
    //here.
}

int main()
{
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
#ifndef ONLINE_JUDGE
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w+", stdout);
#else
// online submission.
#endif
    int x = 0, y = 0, s = 0, t = 0;
    cin >> x >> y >> s >> t;

    return 0;
}